### ISSUE TITLE
[powershell]  ```pdm venv activate``` doesn't work 

### ISSUE THREAD

**Issue by jamestansx** [pdm-project/pdm-venv#10]
**Describe the bug**
```pdm venv activate``` doesn't work in powershell. Calling the command doesn't activate the venv env. 
**To Reproduce**
1. pdm venv create -n test
2. pdm use 
3. pdm venv activate test
4. virtualenv env isn't activated

**Expected behavior**
Calling ```pdm venv activate``` should auto detect the shell used and activate the appropriate script as by manually run ```activate.ps1``` works.

**Screenshots**
![image](https://user-images.githubusercontent.com/45304579/125565004-5c71cb68-e90d-4ac5-b9f7-db93e14537b1.png)

**System (please complete the following information):**
- `pdm-venv` version: 0.2.0
- Python version: 3.9.0
- OS: Windows 21H1

**Additional context**
pdm-venv is installed via ```pdm plugin add pdm-venv```

**Comment by frostming** [comment]
It works, `pdm venv activate <env_name>` only outputs the command and you need to execute yourself, on powershell you can do:

```ps1
. (pdm venv activate)
```

**Comment by jamestansx** [comment]
Tested, it works. Thanks.

**Comment by frostming** [comment]
The activate command changes the current shell process, while `pdm ...` spawns a new process, any modifications based upon that can't impact the current process. Pipenv and Poetry's `shell` command spawns a new process, but with a lot of [bugs and inconsistencies](https://github.com/python-poetry/poetry/issues?q=is%3Aissue+is%3Aopen+shell).

PDM just doesn't want to bother with that. It only adds *a little* effort on the user side without losing any experience of the fancy shell.
