### ISSUE TITLE
Add --version command to pdm-venv

### ISSUE THREAD

**Issue by mcdevitts** [pdm-project/pdm-venv#19]
If a user installs pdm via pipx, and then installs pdm-venv via injection, there is no clear way to check the installed version of pdm-venv. A simple:

pdm venv --version would be helpful.

**Comment by frostming** [comment]
I think `pdm plugin list` can do the trick

**Comment by mcdevitts** [comment]
Yes it does, although it's not where I would think to check.

Frankly, it's also an issue that pipx doesn't show the versions of injected packages.
