### ISSUE TITLE
Support local virtual environment creation

### ISSUE THREAD

**Issue by mcdevitts** [pdm-project/pdm-venv#20]
Would it be possible to support the creation of a virtual environment in the project folder?

pdm-venv allows for easy install and cleanup of virtual environments as well as activation. It would be handy in some cases to create the virtual environment in the project directory.

Thanks for the great work! I've been enjoying pdm and pdm-venv.

**Comment by frostming** [comment]
What should be the name of venv?

1. If you prefer common names like `.venv`, `venv`, just create it via virtualenv tools and pdm can detect them.
2. If you want the name picked by `pdm-venv`, just point `venv.location` to the project root should work.

**Comment by Indiana3714** [comment]
Is there a simple GLOBAL setting for pdm/pdm-venv "venv.location" to point to the local directory? (ie so it works automatically when creating **NEW** projects, just like poetry) The readme on https://github.com/pdm-project/pdm-venv says "Available in Project = No", which doesnt seem to match what I'm/we're looking for?
