### ISSUE TITLE
Is there an option to create the virtualenv in project folder? (similar to Poetry)

### ISSUE THREAD

**Issue by Indiana3714** [pdm-project/pdm-venv#30]
## Is your feature request related to a problem? Please describe.

I still use a virtualenv for my projects since it is easier since VSCode is able to automatically detect a venv folder if it is in the workspace directory, and hence all type hintings/imports get detected automatically without any further steps required.

## Describe the solution you'd like

Something similar that was implemented for Poetry [https://github.com/python-poetry/poetry/issues/108](https://github.com/python-poetry/poetry/issues/108)

Poetry has a config key as follows:
```
virtualenvs.in-project = true
```

**Comment by frostming** [comment]
Duplicate with #20 Close this now
