### ISSUE TITLE
Error message when using the last version of PDM (with integrated venv)

### ISSUE THREAD

**Issue by vadim-su** [pdm-project/pdm-venv#44]
**Describe the bug**
I get an error when running any command
```
Failed to load plugin venv=pdm_venv.plugin:entry_point: cannot import name 'is_venv_python' from 'pdm.utils' (/home/vscode/.local/lib/python3.10/site-packages/pdm/utils.py)
```

**To Reproduce**
1. Install pdm and pdm-venv `pip install --user pdm pdm-venv
2. Run command 'pdm config -vv'
3. See error
```sh
pdm config -vv
Failed to load plugin venv=pdm_venv.plugin:entry_point: cannot import name 'is_venv_python' from 'pdm.utils' (/home/vscode/.local/lib/python3.10/site-packages/pdm/utils.py)
Site/default configuration (/etc/xdg/pdm/config.toml):
# Isolate build environment from the project environment
build_isolation = True
# The root directory of cached files
cache_dir = /home/vscode/.cache/pdm
# Check if there is any newer version available
```

**Expected behavior**
Maybe we should inform users about `pdm-venv` integration because it was a surprise for me and I spent some time defining the problem's origin.

**Screenshots**
![Annoying message](https://user-images.githubusercontent.com/1702003/179346935-6d279355-bd92-463d-9c90-86596a037dfb.png)

**System (please complete the following information):**
- `pdm` version: 2.0.0
- `pdm-venv` version: 0.5.0
- Python version: 3.10.4
- OS: Linux

**Comment by frostming** [comment]
`pdm` 2.0 has builtin support of venv, this plugin is [no longer needed](https://github.com/pdm-project/pdm-venv#deprecation-warning). Thanks
